FROM php:8.1-apache

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Copy mã nguồn vào container
COPY . /var/www/html/

# Copy file cấu hình Apache
COPY ./apache-config.conf /etc/apache2/sites-available/000-default.conf

# Phân quyền
RUN chown -R www-data:www-data /var/www/html
